openapi: 3.0.1
info:
  title: IDPAY Groups of beneficiary API for Initiative
  description: IDPAY Groups of beneficiary for Initiative
  version: '1.0'
servers:
  - url: http://api-io.dev.cstar.pagopa.it/idpay/initiative/group
paths:
  /initiative/{initiativeId}/upload:
    put:
      tags:
        - initiative
      summary: Upload CSV file containing a group of Beneficiary
      operationId: uploadGroupOfBeneficiary
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupUpdateDTO'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '409':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /initiative/{initiativeId}/status:
    get:
      tags:
        - initiative
      summary: Return Group of Beneficiary CSV file upload status with relative error detail if present
      operationId: getGroupOfBeneficiaryStatusAndDetails
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusGroupDTO'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    GroupUpdateDTO:
      type: object
      properties:
        status:
          type: string
        errorRow:
          type: integer
          format: int32
        errorKey:
          type: string
        elabTimeStamp:
          type: string
          format: date-time
    StatusGroupDTO:
      type: object
      properties:
        status:
          type: string
        errorMessage:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
security:
  - Bearer: []
