name: Release

on:
  push:
    branches:
      - main
      - develop
      - uat
    paths-ignore:
      - "CODEOWNERS"
      - "**.md"
      - ".**"

  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - develop
      - uat
    paths-ignore:
      - "CODEOWNERS"
      - "**.md"
      - ".**"

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # ------------------------------
      # CHECKOUT REPOSITORY
      # ------------------------------
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout repository (v6.0.2)
        uses: actions/checkout@dc12339a9823e6625f5410a45b24fcbc55a33ded
        with:
          fetch-depth: 0

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies (secure & immutable)
        run: |
          export YARN_ENABLE_SCRIPTS=false
          yarn install --ignore-scripts --immutable --check-cache

      - name: Generate client API
        run: yarn generate


      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@82bc34a0347019ba8f6d2808cd96cec42ef9620e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn test:coverage
          threshold: 90
          annotations: none
          package-manager: yarn

      - name: SonarQube Scan (PR Analysis)
        uses: SonarSource/sonarqube-scan-action@e9a1c4e09a5eddb7db5d045b83807904bf8f67fc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}"
            -Dsonar.pullrequest.provider=github
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.qualitygate.wait=true
